### ISSUE TITLE
Reporte Practica DLL

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-CxrlosMX#2]
[Reporte_Libreria_DLL.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-CxrlosMX/files/6330117/Reporte_Libreria_DLL.pdf)

**Comment by MLR062998** [comment]
20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
